/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'status' : BookingStatus,
  'bookingId' : IDL.Nat,
  'estimatedDurationMinutes' : IDL.Nat,
  'chargingType' : IDL.Text,
  'vehiclePlate' : IDL.Text,
  'scheduledTime' : IDL.Int,
  'userId' : IDL.Principal,
  'stationId' : IDL.Nat,
});
export const Station = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'chargingTypes' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'longitude' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookSlot' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Int, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'cancelBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAvailableSlots' : IDL.Func(
      [IDL.Nat, IDL.Int, IDL.Int],
      [IDL.Vec(IDL.Record({ 'isAvailable' : IDL.Bool, 'slotTime' : IDL.Int }))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getStationBookings' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getStations' : IDL.Func([], [IDL.Vec(Station)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateStationAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'status' : BookingStatus,
    'bookingId' : IDL.Nat,
    'estimatedDurationMinutes' : IDL.Nat,
    'chargingType' : IDL.Text,
    'vehiclePlate' : IDL.Text,
    'scheduledTime' : IDL.Int,
    'userId' : IDL.Principal,
    'stationId' : IDL.Nat,
  });
  const Station = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'chargingTypes' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'longitude' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookSlot' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Int, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'cancelBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAvailableSlots' : IDL.Func(
        [IDL.Nat, IDL.Int, IDL.Int],
        [
          IDL.Vec(
            IDL.Record({ 'isAvailable' : IDL.Bool, 'slotTime' : IDL.Int })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getStationBookings' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'getStations' : IDL.Func([], [IDL.Vec(Station)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateStationAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };