/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'status' : BookingStatus,
  'bookingId' : bigint,
  'estimatedDurationMinutes' : bigint,
  'chargingType' : string,
  'vehiclePlate' : string,
  'scheduledTime' : bigint,
  'userId' : Principal,
  'stationId' : bigint,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Station {
  'id' : bigint,
  'latitude' : number,
  'chargingTypes' : Array<string>,
  'name' : string,
  'isAvailable' : boolean,
  'longitude' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookSlot' : ActorMethod<[bigint, string, string, bigint, bigint], bigint>,
  'cancelBooking' : ActorMethod<[bigint], boolean>,
  'getAvailableSlots' : ActorMethod<
    [bigint, bigint, bigint],
    Array<{ 'isAvailable' : boolean, 'slotTime' : bigint }>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getStationBookings' : ActorMethod<[bigint], Array<Booking>>,
  'getStations' : ActorMethod<[], Array<Station>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateStationAvailability' : ActorMethod<[bigint, boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];